### ISSUE TITLE
Double spaces persist in HTML version

### ISSUE THREAD

**Issue by gerv** [christi3k/ImportFromEtherpad#3]
Compare
https://etherpad.mozilla.org/cabf-talking-points-cupertino
with
http://wiki-sandbox.allizom.org/CA:CAB_Forum:2015_Cupertino

Etherpad has an irritating bug where it turns some single spaces into double spaces. These seem to persist in the converted pages - see the words "We are" in the section "HTTP Insecure By Default". I can't see why this might be looking at the CSS, but it is.

Gerv

**Comment by christi3k** [comment]
I've experienced the double-spacing too and have never been able to figure out why it happens. The html that's generated by etherpad when this happens seems to be a non-breaking space (nbsp) followed by a regular space. We could replace all instances of this combo (nbsp+space) with a single space. Is that acceptable? Is there any situation where this combo would be desired as-is?
